# Generated by Django 4.0.4 on 2022-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepro',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencepro',
            name='date_start',
            field=models.DateField(),
        ),
    ]
