# Generated by Django 4.0.4 on 2022-05-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=15)),
                ('niveau', models.IntegerField(max_length=3)),
            ],
        ),
    ]
