# Generated by Django 4.0.4 on 2022-05-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='Sujet',
        ),
    ]
